### ISSUE TITLE
Web Presence, Branding

### ISSUE THREAD

**Issue by mishushakov** [GuitarML/SmartGuitarAmp#14]
hey Keith,
i ordered guitarml.com and guitarml.org for the project

<img width="591" alt="Screenshot 2020-11-04 at 13 35 13" src="https://user-images.githubusercontent.com/10400064/98112476-9481c580-1ea2-11eb-8b57-6ee1172b4024.png">

i think they would be great to establish project's web presence and mailing lists for press and stuff
let me know your e-mail (or send greetings to hello at ushakov dot co) so i can donate them to you

thanks

**Comment by GuitarML** [comment]
@mishushakov Wow thank you! Please keep in mind that I have invested next to nothing for this project, and plan on only doing this in my spare time. I think it has a lot of potential as a community project which is why I’m keeping everything free, but I don’t want to set up unrealistic expectations. That being said, that’s great that you’re thinking ahead and I really appreciate the level of involvement you’re putting into it!

The public email for this project is smartguitarml@gmail.com

**Comment by mishushakov** [comment]
All done, you should receive a notification and get access to the domains soon
ps. i'm still the owner, because i haven't yet figured out how setup payment on my behalf otherwise

thanks a lot

**Comment by GuitarML** [comment]
@mishushakov Hey, I’ve given it some thought and I don’t think I’m comfortable with accepting this gift. I really appreciate it, but I wouldn’t want to set up a precedent of accepting any form of monetary donations to my open source project without discussing it beforehand. I hope you understand. If it turns out I really need that domain name, I’ll buy it from you for a premium. Again, hope you understand, but marketing a project is new to me and I want to be careful how I go about doing it.

Sincerely,

Keith

**Comment by mishushakov** [comment]
ugh, very sorry for that, i really did not think about
sorry, but i have to reject your offer to sell it at premium - i'm no squatter

all i want is to make sure our community owns the brand domain names - not me
again, please excuse me for making uncoordinated efforts on community's behalf

**Comment by mishushakov** [comment]
ps. i could return them, but they'll be released into pool and domain catching services would catch and auction them

**Comment by GuitarML** [comment]
@mishushakov Tell you what, let’s continue this discussion via email, send me something to the above email and we can figure it out.
