### ISSUE TITLE
How exactly do the models and plugin work?

### ISSUE THREAD

**Issue by 38github** [GuitarML/SmartGuitarAmp#19]
The little I have used this plugin I am super impressed with the sound, responsiveness when paying, etc. I do have some questions though if I may ask:

1. Do every model have one clean and one driven section? If not will the one it is does not have be silent if chosen?

2. Are the models offered using cab emulation or do we need to add that with for example another plugin?

Thanks in advance!

**Comment by 38github** [comment]
3. The eq sections, are those modelled or added afterwards?

**Comment by GuitarML** [comment]
Good questions, there are two separate models for clean and lead, one trained on clean recordings and one on high gain. Switching the clean/lead loads the appropriate model.

The SmartAmp does not do cab emulation exactly, except for what the recordings were able to capture. Since I recorded from a mic'd amp, some of the impulse response may have been captured, but that's not really what WaveNet is good at modeling.  I'd recommend adding either a separate impulse response plugin or some kind of reverb after for the best sound. Basically, any kind of effect in the time domain (reverb, delay, phase, flange) are difficult for WaveNet to model, but it is good at emulating distortion/overdrive, or any modification to the immediate signal. 

Hope that helps!

**Comment by 38github** [comment]
Thank you for the reply. That cleared some things up.

3. How do I know if I should clean or lead to get the appropriate sound?

4. Have you tried to model an amp with micing up a speaker so that you/we only get the amp and then can add your/ours cab (IR) of choice? I guess that would need a load box or something so that a line level can be taken from the speaker out, right?

Thank you for clearing things up for me and maybe others too.

Regards.

**Comment by GuitarML** [comment]
The implementation for loading custom models is kind of unclear; it won't make a difference which channel you are on when you load a custom .json model. They will sound exactly the same, just with the applicable EQ and Gain settings for that channel. So if you load a model on the clean channel, and then switch to the lead channel and load the same model, they will sound the same as long as the EQ and Gain knobs are set to the same positions. 

It was done that way because the load model feature was added after creating the initial plugin. I'll probably do it differently for any future plugins. 

I have not tried through a speaker, although it would probably be a better way of obtaining the pure amp signal or just taking the line out if the amp has that option.  In the original research paper, they bypassed any speakers at all and drew the signal directly from the amp circuit.  I think they needed to attenuate the signal to get it at the appropriate level. (I wouldn't recommend trying that unless you really know what you're doing on the electronics side).

**Comment by 38github** [comment]
Thank you so much for answering my questions. I really look forward to how this will develop. Also, the cleancompressor model in the tonepack is great to use on many things in a mix and that makes me wants to see more compressor models from people.

**Comment by GuitarML** [comment]
I'd like to test more with compressors too, especially if we can make parametrized models that allow for different settings. That particular model was made using a TC Electronic ForceField Comp, nothing fancy.

**Comment by 38github** [comment]
It compresses in a way that I can't really get any regular compressors to do. It is soft and the tracks sit really nice in the mix. If this technology could get easier on the CPU and easier to use it will be amazing. I can't stand guitar amp emulators, they sound like sudden bursts of distortion and I can't get them to sit in a mix at all. The models you have provided gives me hope!
